export const SEARCH_MOVIES_SUCCESS = 'SEARCH_MOVIES_SUCCESS';
export const SEARCH_MOVIES_FAIL = 'SEARCH_MOVIES_FAIL';
export const VIEW_MOVIE_DETAILS = 'VIEW_MOVIE_DETAILS';
export const RESET_MOVIE_DETAILS = 'RESET_MOVIE_DETAILS'